"""Crie um programa que leia um número de 0 a 20 e mostre seu valor por extenso."""

i = int(input("Digite um numero :    "))
if i == 0:  print("zero")
elif i == 1:print("um")
elif i == 2:print("dois")
elif i == 3:print("três")
elif i == 4:print("quatro")
elif i == 5:print("cinco")
elif i == 6:print("seis")
elif i == 7:print("sete")
elif i == 8:print("oito")
elif i == 9:print("nove")
elif i == 10:print("dez")
elif i == 11:print("onze")
elif i == 12:print("doze")
elif i == 13:print("treze")
elif i == 14:print("quatorze")
elif i == 15:print("quinze")
elif i == 16:print("dezesseis")
elif i == 17:print("dezessete")
elif i == 18:print("dezoito")
elif i == 19:print("dezenove")
elif i == 20:print("vinte")   
elif i > 20 or i < 0:print("invalido. DiGITE UM NÚMERO DE 0 ATÉ 20  ! ")
